version: '3'

networks:
  mernet:
    driver: bridge

services:
  redis:
    image: 'redis'
    container_name: my-redis
    command:
      - --port 0
      - --tls-port 6379
      - --tls-ca-cert-file /cert_redis/ca_certificate.pem
      - --tls-key-file /cert_redis/server_key.pem
      - --tls-cert-file /cert_redis/server_certificate.pem
      - --tls-auth-clients no
    ports:
      - "6379:6379"
    volumes:
      - "~/merlinu/cert_redis:/cert_redis"
    networks:
      - mernet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbit
    tty: true
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - "~/merlinu/rabbbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "~/merlinu/cert_rabbitmq:/cert_rambbitmq"
    networks:
      - mernet
