##########################################################################################
# Customize file classifications.                                                        #
# Results from files under any classifier will be excluded from LGTM                     #
# statistics.                                                                            #
##########################################################################################

##########################################################################################
# Use the `path_classifiers` block to define changes to the default classification of    #
# files.                                                                                 #
##########################################################################################

path_classifiers:
  test:
    # Classify all files in the top-level directories tests/ as test code.
    - exclude: 
    - tests
    - merlin/examples

#########################################################################################
# Use the `queries` block to change the default display of query results.               #
#########################################################################################

queries:
  - include: "*"
  - exclude: "py/clear-text-logging-sensitive-data"

extraction:
  python:
    python_setup:
      version: "3"

