broker:
  cert_reqs: none
  name: rediss
  password: /g/g20/gunny/.merlin/launchit-cz-redis.pass
  port: 30070
  server: cz-gunny-redismerlin.apps.czapps.llnl.gov
  username: ''
  vhost: <vhost>
container:
  config: redis.conf
  config_dir: ./merlin_server/
  format: singularity
  image: redis_latest.sif
  image_type: redis
  pass_file: redis.pass
  pfile: merlin_server.pf
  url: docker://redis
  user_file: redis.users
process:
  kill: kill {pid}
  status: pgrep -P {pid}
results_backend:
  cert_reqs: none
  db_num: 0
  encryption_key: ~/.merlin/encrypt_data_key
  name: rediss
  password: /g/g20/gunny/.merlin/launchit-cz-redis.pass
  port: '30070'
  server: cz-gunny-redismerlin.apps.czapps.llnl.gov
  username: ''
