#!/usr/bin/env python3
import sys


if len(sys.argv) > 1 and sys.argv[1] == 'version':
   print("commands:    		0.48.0\n<This is a fake flux for testing>")
else:
   print("Nodes\n<This is a fake flux for testing>")
