description:
  description: A simple ensemble of echo commands run by flux.
  name: flux_test

batch:
  type: flux
  nodes: 1
  queue: pbatch
  flux_start_opts: -o,-S,log-filename=flux_test.out

env:
  variables:
    OUTPUT_PATH: ./studies
    N_SAMPLES: 10

study:
- description: Echo the params
  name: runs 
  run:
    cmd: $(LAUNCHER) echo "$(V1) $(V2)" > flux_run.out
    task_queue: flux_test
    nodes: 1
    procs: 1
    cores per task: 1

- description: Dump flux info
  name: data
  run:
    cmd: |
      $(SPECROOT)/scripts/flux_info.py > flux_timings.out
    depends: [runs*]
    task_queue: flux_test

global.parameters:
  STUDY:
    label: STUDY.%%
    values:
    - FLUXTEST

merlin:
  resources:
    task_server: celery
    workers:
      simworkers:
        args: -l INFO --concurrency 1 --prefetch-multiplier 1 -Ofair
        steps: [runs, data]
  samples:
    column_labels: [V1, V2]
    file: $(MERLIN_INFO)/samples.npy
    generate:
      cmd: python3 $(SPECROOT)/scripts/make_samples.py -dims 2 -n $(N_SAMPLES) -outfile=$(MERLIN_INFO)/samples.npy 
